### PR TITLE
chore: use plugin TypeScript entry point

### PR DESCRIPTION
**Pull request by ehmicky**
Local Build plugins can directly use the TypeScript entry points. Under the hood, [this calls `ts-node/register`](https://github.com/netlify/build/blob/27299792d4b312ee2ff67d5d1ddb2512cd6c7571/packages/build/src/plugins/child/typescript.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L5).

I believe the `postinstall` script was mostly needed due to the difficulty to test TypeScript local Build plugins in Netlify CI? If so, this new feature might help with this, removing the need for `postinstall`? Please let me know if this is correct.

### CODE REVIEW

**Comment by sbellone** [comment]
@Jerska do you remember? I can't even find any doc about that syntax `[ -d dist/ ]`

**Comment by Jerska** [comment]
`[ -d dist/ ]` just checks if the folder exists.
If it doesn't, it runs `build/`.
If it's possible to dev without, feel free to go with this. :)

**Comment by sbellone** [comment]
Thanks! Will need to be tested then.

**Comment by bodinsamuel** [comment]
Hey @ehmicky 

I have pushed it directly in master, thanks for the notice and the PR 🙏🏻

**Pull request closed without merging**
